# Generated by Django 3.2.4 on 2021-07-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_comentariocontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='coment',
            field=models.TextField(verbose_name='Comentario'),
        ),
    ]
