# Generated by Django 3.2.4 on 2021-07-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_auto_20210719_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='imagen',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='image',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografia'),
        ),
    ]
