# Generated by Django 3.2.4 on 2021-08-14 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0012_rename_imagen_alumnos_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='image',
            new_name='imagen',
        ),
    ]
