# Generated by Django 3.2.4 on 2021-08-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0015_remove_alumnos_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía'),
        ),
    ]
